var LEVEL_BRO = [
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                                                ",
	"                                                             xxxx               ",
	"                                               xxxx                             ",
	"                                        x             xAAAAAAx                  ",
	"                               xxx                    xxxxxxxx                  ",
	"                                                                          c     ",
	" x                     xxxx           xxxx                             xxxxxxx  ",
	" x  @       xxxxxx                                             xx      x     x  ",
	" x          x    x                                                     x     x  ",
	" xxxxxxxxxxxx    xxxxxxxxxxxxxxxxxx              x     xxxxxxxxxxxxxxxxx     x  ",
	"                                  xAAAAAAAAAAAAAAAAAAAAx                     x  ",
	"                                  xxxxxxxxxxxxxxxxxxxxxx                     ",
	"                                                                                ",
	"                                                                                "],
   ["                                                                                           ",
    "                                                                                 c         ",
    "                                                                                xx         ",
    "                                                                                           ",
    "                                                                          xxx              ",
    "                                                                                           ",
    "                                                                 xxxx                      ",
    "                                                                                           ",
    "                                                       xxxxx                               ",
    "                                                                                           ",
    "                                            xxxxxx                                         ",
    "                                                                                           ",
    "                                 xxxxxxx                                                   ",
    "                                                                                           ",
    "                      xxxxxxxx                                                             ",
    "                                                                                           ",
	"           xxxxxxxxx                                                                       ",
    "  @                                                                                        ",
	"xxxxxxxxxxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                                                                              ",
    "                                                                              ",
	"                                                                     c        ",
	"                                                     xxxx        xxAxx        ",
	"                                                                              ",
	"                                                                              ",
	"            AxxA         xxx       xAx       xxxx                             ",
	"                                                                              ",
	"     AAxx                                                                     ",
	"                                                                              ",
	"                                                                             ",
	"                xxx         xxx          xxx          xxx           xxx       ",
	"                                                                              ",
	"                                                                              ",
	"      xxxxxxx             xxxxxxx         xxxxx                               ",
	"                                                                              ",
	"                                                                              ",
	"                  xxxAxxx      xxx            xxxxx                           ",                   
	"                                                                              ",
	"           @                                                                  ",
	"         xxxxxx                       AAxxxxAAA        xxxxxxx                ",
	"x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],	
   ];

if (typeof module != "undefined" && module.exports) {
	module.exports = LEVEL_BRO
}